### ISSUE TITLE
The distribution of poses

### ISSUE THREAD

**Issue by yufu-liu** [sha2nkt/ipman-r#2]
Hi, thanks for this inspiring paper!
I am curious about the scatter plot for distribution of poses on page 9 because I want to visualize my datasets, too.
Although I know it was produced by t-SNE, I still wonder how to process the poses with different frame numbers.

**Comment by sha2nkt** [comment]
Hi, 
I released the script we used for the tsne plot [here](https://github.com/sha2nkt/moyo_toolkit/blob/master/moyo/scripts/plot_tsne.py).

**Comment by yufu-liu** [comment]
Hi, I really appreciate your sharing and will try it later!
