### ISSUE TITLE
Demo Code: Running on In-the-Wild Images

### ISSUE THREAD

**Issue by AmoghTiwari** [sha2nkt/ipman-r#3]
Hi,

Are there any plans to publicly release a demo script, using which we can test the method on in-the-wild images

**Comment by sha2nkt** [comment]
Hi, 
We will release a demo shortly. In the meantime, our weights are fully compatible with the [SPIN demo](https://github.com/nkolot/SPIN#run-demo-code) code and that demo should work off-the-shelf with our released checkpoints.

**Comment by AmoghTiwari** [comment]
Okay. Thanks for the clarification. I'll try out the demo with SPIN code. 
Closing this issue for now.

**Comment by jackieyung** [comment]
> Hi, We will release a demo shortly. In the meantime, our weights are fully compatible with the [SPIN demo](https://github.com/nkolot/SPIN#run-demo-code) code and that demo should work off-the-shelf with our released checkpoints.

Hello, thanks for your cool work. I'm also looking forward to your demo code release. Thanks a lot.
